Removed warnings from configure script on linux machines.
Symptom - warnings of libraries not found on linux (64 only?)
Cause   - when commenting out sections of the SSE3 code, the apple section of
          the script was found to cause the problem. The block quotes around
          macros are unnecessary, and must have been doing something in the
          autoconfigure script.
Solution- removed the block quotes.

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -3146,6 +3146,69 @@ esac
 
 case ${OS_INFORMATION} in
 	*-apple-*)
+		if test $USE_SSE3 = "true"; then
+  { echo "$as_me:$LINENO: checking for pmmintrin.h" >&5
+echo $ECHO_N "checking for pmmintrin.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_pmmintrin_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+{ { echo "$as_me:$LINENO: error: Cannot compile with SSE3 instructions
+See \`config.log' for more details." >&5
+echo "$as_me: error: Cannot compile with SSE3 instructions
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+
+#include <pmmintrin.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_header_pmmintrin_h=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_header_pmmintrin_h=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_pmmintrin_h" >&5
+echo "${ECHO_T}$ac_cv_header_pmmintrin_h" >&6; }
+if test $ac_cv_header_pmmintrin_h = yes; then
+  CFLAGS="-msse3 $CFLAGS";OUSE_SSE3="
+else
+  use_sse3"
+fi
+
+
+else
+  { echo "$as_me:$LINENO: result: not using SSE3" >&5
+echo "${ECHO_T}not using SSE3" >&6; }
+fi
+
+		;;
+	*)
 		ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -3914,155 +3977,6 @@ echo "${ECHO_T}$ac_cv_header_pmmintrin_h" >&6; }
 
 fi
 if test $ac_cv_header_pmmintrin_h = yes; then
-  CFLAGS="-msse3 $CFLAGS";OUSE_SSE3=",use_sse3"
-else
-  { { echo "$as_me:$LINENO: error: Cannot compile with SSE3 instructions
-See \`config.log' for more details." >&5
-echo "$as_me: error: Cannot compile with SSE3 instructions
-See \`config.log' for more details." >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-
-else
-  { echo "$as_me:$LINENO: result: not using SSE3" >&5
-echo "${ECHO_T}not using SSE3" >&6; }
-fi
-
-		;;
-	*)
-		if test $USE_SSE3 = "true"; then
-  if test "${ac_cv_header_pmmintrin_h+set}" = set; then
-  { echo "$as_me:$LINENO: checking for pmmintrin.h" >&5
-echo $ECHO_N "checking for pmmintrin.h... $ECHO_C" >&6; }
-if test "${ac_cv_header_pmmintrin_h+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_header_pmmintrin_h" >&5
-echo "${ECHO_T}$ac_cv_header_pmmintrin_h" >&6; }
-else
-  # Is the header compilable?
-{ echo "$as_me:$LINENO: checking pmmintrin.h usability" >&5
-echo $ECHO_N "checking pmmintrin.h usability... $ECHO_C" >&6; }
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-$ac_includes_default
-#include <pmmintrin.h>
-_ACEOF
-rm -f conftest.$ac_objext
-if { (ac_try="$ac_compile"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_compile") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && {
-	 test -z "$ac_c_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest.$ac_objext; then
-  ac_header_compiler=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-	ac_header_compiler=no
-fi
-
-rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
-{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
-echo "${ECHO_T}$ac_header_compiler" >&6; }
-
-# Is the header present?
-{ echo "$as_me:$LINENO: checking pmmintrin.h presence" >&5
-echo $ECHO_N "checking pmmintrin.h presence... $ECHO_C" >&6; }
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <pmmintrin.h>
-_ACEOF
-if { (ac_try="$ac_cpp conftest.$ac_ext"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } >/dev/null && {
-	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
-	 test ! -s conftest.err
-       }; then
-  ac_header_preproc=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-  ac_header_preproc=no
-fi
-
-rm -f conftest.err conftest.$ac_ext
-{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
-echo "${ECHO_T}$ac_header_preproc" >&6; }
-
-# So?  What about this header?
-case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
-  yes:no: )
-    { echo "$as_me:$LINENO: WARNING: pmmintrin.h: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: pmmintrin.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: pmmintrin.h: proceeding with the compiler's result" >&5
-echo "$as_me: WARNING: pmmintrin.h: proceeding with the compiler's result" >&2;}
-    ac_header_preproc=yes
-    ;;
-  no:yes:* )
-    { echo "$as_me:$LINENO: WARNING: pmmintrin.h: present but cannot be compiled" >&5
-echo "$as_me: WARNING: pmmintrin.h: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: pmmintrin.h:     check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: pmmintrin.h:     check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: pmmintrin.h: see the Autoconf documentation" >&5
-echo "$as_me: WARNING: pmmintrin.h: see the Autoconf documentation" >&2;}
-    { echo "$as_me:$LINENO: WARNING: pmmintrin.h:     section \"Present But Cannot Be Compiled\"" >&5
-echo "$as_me: WARNING: pmmintrin.h:     section \"Present But Cannot Be Compiled\"" >&2;}
-    { echo "$as_me:$LINENO: WARNING: pmmintrin.h: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: pmmintrin.h: proceeding with the preprocessor's result" >&2;}
-    { echo "$as_me:$LINENO: WARNING: pmmintrin.h: in the future, the compiler will take precedence" >&5
-echo "$as_me: WARNING: pmmintrin.h: in the future, the compiler will take precedence" >&2;}
-    ( cat <<\_ASBOX
-## ------------------------------------ ##
-## Report this to poy4@googlegroups.com ##
-## ------------------------------------ ##
-_ASBOX
-     ) | sed "s/^/$as_me: WARNING:     /" >&2
-    ;;
-esac
-{ echo "$as_me:$LINENO: checking for pmmintrin.h" >&5
-echo $ECHO_N "checking for pmmintrin.h... $ECHO_C" >&6; }
-if test "${ac_cv_header_pmmintrin_h+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_cv_header_pmmintrin_h=$ac_header_preproc
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_header_pmmintrin_h" >&5
-echo "${ECHO_T}$ac_cv_header_pmmintrin_h" >&6; }
-
-fi
-if test $ac_cv_header_pmmintrin_h = yes; then
   { echo "$as_me:$LINENO: checking for posix_memalign" >&5
 echo $ECHO_N "checking for posix_memalign... $ECHO_C" >&6; }
 if test "${ac_cv_func_posix_memalign+set}" = set; then
@@ -4145,8 +4059,7 @@ fi
 { echo "$as_me:$LINENO: result: $ac_cv_func_posix_memalign" >&5
 echo "${ECHO_T}$ac_cv_func_posix_memalign" >&6; }
 if test $ac_cv_func_posix_memalign = yes; then
-  CFLAGS="-msse3 $CFLAGS";OUSE_SSE3=",use_sse3";{ echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
+  CFLAGS="-msse3 $CFLAGS";OUSE_SSE3=",use_sse3"
 else
   { { echo "$as_me:$LINENO: error: posix_memalign not found
 See \`config.log' for more details." >&5
